name: Setup Amber Compiler
description: Download an Amber compiler.
branding:
  color: orange
  icon: download
inputs:
  amber-version:
    description: The version of Amber to install.
    default: 0.5.1-alpha
  amber-repository-url:
    description: >-
      The Git repository URL to clone Amber from when building from source.
      Defaults to the official Amber repository.
    default: https://github.com/amber-lang/amber.git
  amber-repository-ref:
    description: >-
      A Git ref (commit SHA, branch name, or tag name) to build Amber from source.
      If provided, this overrides 'amber-version' and triggers a build from source.
    default: ""
  enable-cache:
    description: Whether to cache Amber binaries.
    default: true
  cache-path:
    description: >-
      The path to directory where Amber binary caches are stored.
      If empty string is given, defaults to ~/.tools on the runner.
    default: ""
  bin-path:
    description: >-
      The path to location where the final amber binary should be located.
      Default to `/usr/local/bin/amber`.
    default: /usr/local/bin/amber
outputs:
  amber-path:
    description: The path where the Amber binary was installed.
    value: ${{ steps.main.outputs.amber-path }}
runs:
  using: composite
  steps:
    - shell: bash
      env:
        INPUT_CACHE_PATH: ${{ inputs.cache-path }}
      id: cache-path
      run: |
        # Handle user-given cache-path
        delimiter="ghadelimiter_$(openssl rand -hex 16)"
        cache_path="${INPUT_CACHE_PATH:-$HOME/.tools}"
        {
          echo "amber_cache_path<<$delimiter"
          echo "$cache_path"
          echo "$delimiter"
        } >> "$GITHUB_OUTPUT"
    - name: Cache Amber binaries
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      id: amber-cache
      if: inputs.enable-cache
      with:
        path: ${{ steps.cache-path.outputs.amber_cache_path }}/amber
        key: >-
          setup-amber-${{ runner.os }}-${{ runner.arch }}-${{ inputs.amber-repository-ref || inputs.amber-version }}
    - name: Determine source directory
      if: inputs.amber-repository-ref != '' && steps.amber-cache.outputs.cache-hit != 'true'
      id: source-dir
      shell: bash
      env:
        ENABLE_CACHE: ${{ inputs.enable-cache }}
        CACHE_PATH: ${{ steps.cache-path.outputs.amber_cache_path }}
        RUNNER_TEMP: ${{ runner.temp }}
      run: |
        if [ "$ENABLE_CACHE" = "true" ]; then
          src_dir="$CACHE_PATH/amber-source"
        else
          src_dir="$RUNNER_TEMP/amber-source"
        fi
        echo "src_dir=$src_dir" >> "$GITHUB_OUTPUT"
    - name: Checkout Amber source
      if: inputs.amber-repository-ref != '' && steps.amber-cache.outputs.cache-hit != 'true'
      shell: bash
      env:
        SOURCE_DIR: ${{ steps.source-dir.outputs.src_dir }}
        REPO_URL: ${{ inputs.amber-repository-url }}
        REPO_REF: ${{ inputs.amber-repository-ref }}
      run: |
        dest_dir="$SOURCE_DIR"
        echo "::debug::Checking out Amber source to $dest_dir"
        if [ -d "$dest_dir/.git" ]; then
          echo "Source already exists in $dest_dir"
        else
          mkdir -p "$dest_dir"
          cd "$dest_dir"
          git init
          # Use the token for authentication if it's a GitHub URL
          url="$REPO_URL"
          if [[ "$url" == "https://github.com/"* ]]; then
            url="${url/https:\/\/github.com\//https://x-access-token:$GITHUB_TOKEN@github.com/}"
          fi
          git remote add origin "$url"
          git fetch --depth 1 origin "$REPO_REF"
          git checkout FETCH_HEAD
        fi
    - name: Cache Rust build artifacts
      uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      if: inputs.amber-repository-ref != '' && steps.amber-cache.outputs.cache-hit != 'true'
      with:
        workspaces: ${{ steps.source-dir.outputs.src_dir }} -> target
    - id: main
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        SETUP_AMBER_CACHE_PATH: ${{ steps.cache-path.outputs.amber_cache_path }}
        SETUP_AMBER_BIN_PATH: ${{ inputs.bin-path }}
        SETUP_AMBER_VERSION: ${{ inputs.amber-version }}
        SETUP_AMBER_REPOSITORY_URL: ${{ inputs.amber-repository-url }}
        SETUP_AMBER_REPOSITORY_REF: ${{ inputs.amber-repository-ref }}
        SETUP_AMBER_SOURCE_DIR: ${{ steps.source-dir.outputs.src_dir }}
      run: |
        # Download Amber binary
        bash "$ACTION_PATH/dist/main.sh"
